In [4]:
a = [1,2,3,4]

In [5]:
a[2]

3

In [6]:
dd=[
    [1,2,3],
    [4,5,6],
    [7,8,9]
]

In [7]:
dd[0][2]

3

In [8]:
dd[0]

[1, 2, 3]

In [9]:
#张量的秩决定轴的个数，轴的长度决定张量的形状

In [10]:
import torch

In [11]:
t = torch.tensor(dd)
t


tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [12]:
type(t)

torch.Tensor

In [13]:
t.shape

torch.Size([3, 3])

3*3的形状告诉我们这个秩为2的张量，每个轴的长度为3（每个轴上3个索引）

In [14]:
#重塑

In [15]:
t.reshape(1,9)

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [16]:
t.reshape(1,9).shape

torch.Size([1, 9])

张量的形状编码了所有关于张量、轴、秩和索引的相关信息

CNN通常为4通道len([?,?,?,?])=4
[batch_size,colour,height,weight]

In [17]:
import numpy as np

In [18]:
print(t.dtype)
print(t.device)
print(t.layout)

torch.int64
cpu
torch.strided


In [19]:
device = torch.device('cuda:0')
device

device(type='cuda', index=0)

In [20]:
t1 = torch.tensor([1,2,3])
t2 = torch.tensor([1.,2.,3.])

In [21]:
t1.dtype

torch.int64

In [22]:
t2.dtype

torch.float32

In [23]:
t1+t2

tensor([2., 4., 6.])

In [24]:
t1 = torch.tensor([1,2,3])
t2 = t1.cuda()

In [25]:
t1.device

device(type='cpu')

In [26]:
t2.device

device(type='cuda', index=0)

In [27]:
t1+t2

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

这段代码期望有一个torch.longtensor，但是找到了一个GPU版本的torch.cuda.longtensor

In [39]:
data = np.array([1,2,3])
type(data)

numpy.ndarray

In [40]:
torch.Tensor(data)

tensor([1., 2., 3.])

In [41]:
torch.tensor(data)

tensor([1, 2, 3], dtype=torch.int32)

In [42]:
torch.as_tensor(data)

tensor([1, 2, 3], dtype=torch.int32)

In [43]:
torch.from_numpy(data)

tensor([1, 2, 3], dtype=torch.int32)

In [44]:
torch.eye(10)

tensor([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [45]:
torch.zeros(2,2)

tensor([[0., 0.],
        [0., 0.]])

In [46]:
torch.ones(2,2)

tensor([[1., 1.],
        [1., 1.]])

In [47]:
torch.rand(2,2)

tensor([[0.4873, 0.7331],
        [0.1313, 0.5191]])

In [48]:
torch.get_default_dtype()

torch.float32

In [49]:
torch.tensor(np.array([1,2,3]))

tensor([1, 2, 3], dtype=torch.int32)

In [50]:
torch.tensor(np.array([1.,2.,3.]))

tensor([1., 2., 3.], dtype=torch.float64)

In [51]:
torch.tensor(np.array([1,2,3]),dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [52]:
data=np.array([1,2,3])
data

array([1, 2, 3])

In [53]:
t1 = torch.Tensor(data)
t2 = torch.tensor(data)
t3 = torch.as_tensor(data)
t4 = torch.from_numpy(data)

In [54]:
data[0] = 0
data[1] = 0
data[2] = 0

In [55]:
print(t1)
print(t2)

tensor([1., 2., 3.])
tensor([1, 2, 3], dtype=torch.int32)


In [56]:
print(t3)
print(t4)

tensor([0, 0, 0], dtype=torch.int32)
tensor([0, 0, 0], dtype=torch.int32)


torch.tensor()
torch.as_tensor()
常用

In [57]:
t = torch.tensor([
    [1,1,1,1],
    [2,2,2,2],
    [3,3,3,3],
    [4,4,4,4]
],dtype=torch.float64)

In [58]:
t.size()

torch.Size([4, 4])

In [59]:
t.shape

torch.Size([4, 4])

In [60]:
len(t.shape)

2

In [61]:
torch.tensor(t.shape).prod()

tensor(16)

In [62]:
t.numel()

16

In [63]:
t.reshape(1,16)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3., 4., 4., 4., 4.]],
       dtype=torch.float64)

In [64]:
t.reshape(4,4)

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.]], dtype=torch.float64)

In [65]:
t.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[2., 2.],
          [2., 2.]]],


        [[[3., 3.],
          [3., 3.]],

         [[4., 4.],
          [4., 4.]]]], dtype=torch.float64)

In [66]:
print(t.reshape(1,16))
print(t.reshape(1,16).shape)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3., 4., 4., 4., 4.]],
       dtype=torch.float64)
torch.Size([1, 16])


In [67]:
print(t.reshape(1,16).squeeze().unsqueeze(dim=0))
print(t.reshape(1,16).squeeze().unsqueeze(dim=0).shape)

tensor([[1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3., 4., 4., 4., 4.]],
       dtype=torch.float64)
torch.Size([1, 16])


In [68]:
print(t.reshape(1,16).squeeze())
print(t.reshape(1,16).squeeze().shape)

tensor([1., 1., 1., 1., 2., 2., 2., 2., 3., 3., 3., 3., 4., 4., 4., 4.],
       dtype=torch.float64)
torch.Size([16])


压缩一个张量可以移除所有长度为1的轴，而解缩一个张量则会增加一个长度为1的维度

张量的轴变平

In [78]:
t1 = torch.tensor([
    [1,1,1],
    [1,1,1],
    [1,1,1]
])
t2 = torch.tensor([
    [2,2,2],
    [2,2,2],
    [2,2,2]
])
t3 = torch.tensor([
    [3,3,3],
    [3,3,3],
    [3,3,3]
])

In [80]:
t = torch.stack((t1,t2,t3))
t.shape

torch.Size([3, 3, 3])

In [81]:
t

tensor([[[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]],

        [[2, 2, 2],
         [2, 2, 2],
         [2, 2, 2]],

        [[3, 3, 3],
         [3, 3, 3],
         [3, 3, 3]]])

In [84]:
t = t.reshape(3,1,3,3)

In [85]:
t

tensor([[[[1, 1, 1],
          [1, 1, 1],
          [1, 1, 1]]],


        [[[2, 2, 2],
          [2, 2, 2],
          [2, 2, 2]]],


        [[[3, 3, 3],
          [3, 3, 3],
          [3, 3, 3]]]])

In [86]:
t[0]

tensor([[[1, 1, 1],
         [1, 1, 1],
         [1, 1, 1]]])

In [87]:
t[0][0]

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])

In [88]:
t[0][0][0]

tensor([1, 1, 1])

In [89]:
t[0][0][0][0]

tensor(1)

In [91]:
t.reshape(1,-1)[0]

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3,
        3, 3, 3])

In [92]:
t.reshape(-1)

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3,
        3, 3, 3])

In [93]:
t.view(t.numel())

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3,
        3, 3, 3])

In [94]:
t.flatten()

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3,
        3, 3, 3])

In [95]:
t.flatten(start_dim=1).shape

torch.Size([3, 9])

In [101]:
t.flatten(start_dim=1)

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [104]:
t  =torch.tensor([
    [0,1,0],
    [2,0,2],
    [0,3,0]
],dtype=torch.float32)

In [105]:
t.sum()

tensor(8.)

In [106]:
t.numel()

9

In [108]:
t.sum().numel()

1

In [109]:
t.sum().numel()<t.numel()

True

In [110]:
t.prod()

tensor(0.)

In [111]:
t.mean()

tensor(0.8889)

In [112]:
t.std()

tensor(1.1667)